# SwiftLint Configuration for WeatherApp
# Staff-level config: enfocada en robustez, legibilidad, mantenibilidad

included:
  - Sources
  - WeatherApp
  - Tests

excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - fastlane
  - .git
  - Generated # <- si usas código generado

# Desactivadas: se manejan por herramientas externas (editor/linter/IDE)
disabled_rules:
  - trailing_whitespace
  - file_header
  - todo
  - identifier_name # Lo personalizamos abajo

# Reglas estrictas habilitadas manualmente
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - force_cast
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - no_space_in_method_call
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - private_outlet # fuerza IBOutlet privados
  - switch_case_alignment
  - strong_iboutlet
  - discouraged_direct_init
  - discouraged_object_literal

# Límite de líneas por archivo
file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

# Límites de longitud de línea
line_length:
  warning: 120
  error: 140
  ignores_comments: true
  ignores_function_declarations: true
  ignores_urls: true

# Tamaño de funciones
function_body_length:
  warning: 40
  error: 80

# Número de parámetros
function_parameter_count:
  warning: 5
  error: 7

# Tamaño de tipo (class/struct/enum)
type_body_length:
  warning: 250
  error: 400

# Complejidad ciclomática
cyclomatic_complexity:
  warning: 10
  error: 15

# Profundidad de nesting
nesting:
  type_level:
    warning: 3
  function_level:
    warning: 4

# Nombres de identificadores
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 30
    error: 40
  excluded:
    - id
    - URL
    - url
    - x
    - y

# Tuplas grandes
large_tuple:
  warning: 3
  error: 4

# Reglas personalizadas (alta señal, baja fricción)
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    match_kinds: identifier
    message: "Avoid using print(). Use os_log or unified logging instead."
    severity: warning

  no_debug:
    name: "No Debug Flags"
    regex: "#if DEBUG"
    message: "Use a debug configuration flag or dependency injection instead of preprocessor checks."
    severity: warning

  no_force_try:
    name: "No force try"
    regex: "try!"
    message: "Avoid 'try!'. Handle errors explicitly or use optional try?"
    severity: error

# Analyzer rules (requieren 'swiftlint analyze')
analyzer_rules:
  - unused_declaration # ayuda a detectar código muerto

# Report format
reporter: "xcode"
